version: "3.3"
services:
#  front:
#    image: "node:10-alpine"
#    user: "node"
#    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ./front:/home/node/app
#    ports:
#      - "8080:8080"
#    command: [sh, -c, "npm install && npm run start"]
  back:
    image: "node:10-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./back:/home/node/app
    ports:
      - "3000:3000"
    command: [sh, -c, "npm install && npm start"]
