export const ADD_TICKET = "ADD_TICKET";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const LOAD_TICKETS = "LOAD_TICKETS";
export const LOAD_USERS = "LOAD_USERS";
export const CHANGE_ASSIGNEE = "CHANGE_ASSIGNEE";