const PRIORITY_NEW = "New";
const PRIORITY_BLOCKER = "Blocker";
const PRIORITY_HIGH = "High";
const PRIORITY_MEDIUM = "Medium";
const PRIORITY_LOW = "Low";

const PRIORITIES_LIST = [PRIORITY_NEW, PRIORITY_BLOCKER, PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW];


export {PRIORITY_NEW, PRIORITY_BLOCKER, PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW, PRIORITIES_LIST};