const STATUS_NEW = "New";
const STATUS_PROGRESS = "In Progress";
const STATUS_REVIEW = "In Review";
const STATUS_DONE = "Done";

const STATUSES_LIST = [STATUS_NEW, STATUS_PROGRESS, STATUS_REVIEW, STATUS_DONE];


export {STATUS_NEW, STATUS_PROGRESS, STATUS_REVIEW, STATUS_DONE, STATUSES_LIST};